# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               American Discourse
tagline:             'Is America Great Yet?'
description:         'Is America Great Yet?'
url:                 http://americandiscourse.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              American Discourse
  url:               https://twitter.com/mdo
  email:             therebellion@protonmail.com

# Custom vars
version:             1.0.0
gems:                [jekyll-paginate]
